### ISSUE TITLE
commandline commands for SteamAccountSwitcher?

### ISSUE THREAD

**Issue by o0Julia0o** [sahin-a/SteamAccountManager#38]
It would be nice, if you could use command line commands to switch accounts. So you could start or end other programs. F.e. if you start Game X on account Y you could start winamp with commmandline commands with playlist x. After the game is quit, you could quit winamp automatically too. So it has to be possible to define configuration x with the Switcher. X = Loginto Account X f.e.

**Comment by sahin-a** [comment]
Hello Julia, I'll look into creating a cli version today for command based interaction.

**Comment by o0Julia0o** [comment]
That sounds nice! Thank you.

**Comment by sahin-a** [comment]
Just started working on it. Do you have any other command suggestions except for switching accounts and listing account details?

**Comment by o0Julia0o** [comment]
Nice to hear :) Switching account is the function i would use everytime. So that would be beautiful. A No-gui usebilityl would be nice to have. So SteamAccountManager.exe start account Julia. Or SteamAccountManager switch account sahin. That´s what i would use it for in a batch-file.

If there could be a errorlevel-code like 1 for choosen steamaccount successfully logged in or 0 for not, would be nice. So i can grab this errorlevel to let my bach choose what next to do.

**Comment by sahin-a** [comment]
Hier erstmal eine kleine Testversion. Ist noch nicht final, muss da noch ein wenig refactoren und rumschrauben. Feedback wär nice falls dir was auffällt oder etwas nicht nice ist. Mit Konsolenanwendungen hatte ich bis jetzt nicht viel zu tun mit.

Beispiele
```
SteamAccountManager.CLI.exe switch -n="julia"
SteamAccountManager.CLI.exe switch /accountname="julia"
SteamAccountManager.CLI.exe s-n="julia"
[...]

SteamAccountManager.CLI.exe list
SteamAccountManager.CLI.exe l

SteamAccountManager.CLI.exe -h
```

Help Output
```
list|l (Default): Lists all accounts tracked by steam

   switch|s: Switches to the specified account name
        /n /a /accountname : account name to switch to (String) (Required)

   Global Parameters:
        /debug    :
        /help|h|? : Help
```

Ist ein wenig komisch mit dem aufgezwungenen ="", werde aber nochmal nachschauen ob ich das nicht noch anpassen kann in der verwendeten Library. Notfalls werde ich wohl meinen eigenen Command Parser schreiben müssen.

[steam_account_switcher_cli_debug_dev_build.zip](https://github.com/sahin-a/SteamAccountSwitcher/files/10117695/steam_account_switcher_cli_debug_dev_build.zip)

**Comment by o0Julia0o** [comment]
Ich erhalte folgendes, wenn ich den Befehl: SteamAccountManager.CLI.exe list absetze: A fatal error occurred. The required library hostfxr.dll could not be found.

.NET 6.0 SDK (v6.0.403) ist installiert.

**Comment by sahin-a** [comment]
Probiers mal mit diesem Build. Habe es diesmal im Release Build gebaut. Die Runtime liefert er hier mit.

```
Exit Codes
0 - Success
1 - Failure
```

[SteamAccountManager.CLI_Testversion_WinX64_Standalone.zip](https://github.com/sahin-a/SteamAccountSwitcher/files/10135979/SteamAccountManager.CLI_Testversion_WinX64_Standalone.zip)

**Comment by sahin-a** [comment]
Versehentlich das Issue geschlossen, hats funktioniert?

**Comment by sahin-a** [comment]
No further replies happened
